/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#0A0A0A",
        foreground: "#FFFFFF",
        card: "#1A1A2E",
        "card-foreground": "#FFFFFF",
        popover: "#1A1A2E",
        "popover-foreground": "#FFFFFF",
        primary: "#00FFFF",
        "primary-foreground": "#0A0A0A",
        secondary: "#0080FF",
        "secondary-foreground": "#FFFFFF",
        muted: "#2A2A3E",
        "muted-foreground": "#B0B0B0",
        accent: "#00FFFF",
        "accent-foreground": "#0A0A0A",
        destructive: "oklch(0.577 0.245 27.325)",
        border: "#333344",
        input: "#333344",
        ring: "#00FFFF",
        "chart-1": "#00FFFF",
        "chart-2": "#0080FF",
        "chart-3": "#4040FF",
        "chart-4": "#8080FF",
        "chart-5": "#C0C0FF",
        sidebar: "#1A1A2E",
        "sidebar-foreground": "#FFFFFF",
        "sidebar-primary": "#00FFFF",
        "sidebar-primary-foreground": "#0A0A0A",
        "sidebar-accent": "#0080FF",
        "sidebar-accent-foreground": "#FFFFFF",
        "sidebar-border": "#333344",
        "sidebar-ring": "#00FFFF",
      },
      animation: {
        'float': 'float 6s ease-in-out infinite',
        'glow': 'glow 2s ease-in-out infinite alternate',
        'typing': 'typing 3.5s steps(40, end)',
        'blink': 'blink 0.75s step-end infinite',
        'shimmer': 'shimmer 2s infinite',
      },
    },
  },
  plugins: [],
}